# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: cannon.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='cannon.proto',
  package='wallu.hud',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x0c\x63\x61nnon.proto\x12\twallu.hud\"\x9f\x02\n\x0c\x43\x61nnonStatus\x12\x14\n\x0cmotor_status\x18\x01 \x01(\t\x12\x12\n\nshot_count\x18\x02 \x01(\x05\x12\x14\n\x0cwarmup_timer\x18\x03 \x01(\x05\x12\x17\n\x0fwarmup_duration\x18\x04 \x01(\x05\x12\x18\n\x10warmup_timer_end\x18\x05 \x01(\x05\x12\x16\n\x0e\x63ooldown_timer\x18\x06 \x01(\x05\x12\x19\n\x11\x63ooldown_duration\x18\x07 \x01(\x05\x12\x1a\n\x12\x63ooldown_timer_end\x18\x08 \x01(\x05\x12\x16\n\x0eoverheat_timer\x18\t \x01(\x05\x12\x19\n\x11overheat_duration\x18\n \x01(\x05\x12\x1a\n\x12overheat_timer_end\x18\x0b \x01(\x05\"\x82\x01\n\rCannonCommand\x12+\n\x04type\x18\x01 \x01(\x0e\x32\x1d.wallu.hud.CannonCommand.Type\"D\n\x04Type\x12\x0c\n\x08SHUTDOWN\x10\x00\x12\x10\n\x0cMOTOR_WARMUP\x10\x01\x12\x12\n\x0eMOTOR_COOLDOWN\x10\x02\x12\x08\n\x04\x46IRE\x10\x03\x62\x06proto3'
)



_CANNONCOMMAND_TYPE = _descriptor.EnumDescriptor(
  name='Type',
  full_name='wallu.hud.CannonCommand.Type',
  filename=None,
  file=DESCRIPTOR,
  create_key=_descriptor._internal_create_key,
  values=[
    _descriptor.EnumValueDescriptor(
      name='SHUTDOWN', index=0, number=0,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='MOTOR_WARMUP', index=1, number=1,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='MOTOR_COOLDOWN', index=2, number=2,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='FIRE', index=3, number=3,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=380,
  serialized_end=448,
)
_sym_db.RegisterEnumDescriptor(_CANNONCOMMAND_TYPE)


_CANNONSTATUS = _descriptor.Descriptor(
  name='CannonStatus',
  full_name='wallu.hud.CannonStatus',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='motor_status', full_name='wallu.hud.CannonStatus.motor_status', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='shot_count', full_name='wallu.hud.CannonStatus.shot_count', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='warmup_timer', full_name='wallu.hud.CannonStatus.warmup_timer', index=2,
      number=3, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='warmup_duration', full_name='wallu.hud.CannonStatus.warmup_duration', index=3,
      number=4, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='warmup_timer_end', full_name='wallu.hud.CannonStatus.warmup_timer_end', index=4,
      number=5, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='cooldown_timer', full_name='wallu.hud.CannonStatus.cooldown_timer', index=5,
      number=6, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='cooldown_duration', full_name='wallu.hud.CannonStatus.cooldown_duration', index=6,
      number=7, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='cooldown_timer_end', full_name='wallu.hud.CannonStatus.cooldown_timer_end', index=7,
      number=8, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='overheat_timer', full_name='wallu.hud.CannonStatus.overheat_timer', index=8,
      number=9, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='overheat_duration', full_name='wallu.hud.CannonStatus.overheat_duration', index=9,
      number=10, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='overheat_timer_end', full_name='wallu.hud.CannonStatus.overheat_timer_end', index=10,
      number=11, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=28,
  serialized_end=315,
)


_CANNONCOMMAND = _descriptor.Descriptor(
  name='CannonCommand',
  full_name='wallu.hud.CannonCommand',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='type', full_name='wallu.hud.CannonCommand.type', index=0,
      number=1, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
    _CANNONCOMMAND_TYPE,
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=318,
  serialized_end=448,
)

_CANNONCOMMAND.fields_by_name['type'].enum_type = _CANNONCOMMAND_TYPE
_CANNONCOMMAND_TYPE.containing_type = _CANNONCOMMAND
DESCRIPTOR.message_types_by_name['CannonStatus'] = _CANNONSTATUS
DESCRIPTOR.message_types_by_name['CannonCommand'] = _CANNONCOMMAND
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

CannonStatus = _reflection.GeneratedProtocolMessageType('CannonStatus', (_message.Message,), {
  'DESCRIPTOR' : _CANNONSTATUS,
  '__module__' : 'cannon_pb2'
  # @@protoc_insertion_point(class_scope:wallu.hud.CannonStatus)
  })
_sym_db.RegisterMessage(CannonStatus)

CannonCommand = _reflection.GeneratedProtocolMessageType('CannonCommand', (_message.Message,), {
  'DESCRIPTOR' : _CANNONCOMMAND,
  '__module__' : 'cannon_pb2'
  # @@protoc_insertion_point(class_scope:wallu.hud.CannonCommand)
  })
_sym_db.RegisterMessage(CannonCommand)


# @@protoc_insertion_point(module_scope)
