# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: motor_requests.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='motor_requests.proto',
  package='wallu.motor_requests',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x14motor_requests.proto\x12\x14wallu.motor_requests\"\xa8\x01\n\x0cMotorRequest\x12\x10\n\x08throttle\x18\x01 \x01(\x05\x12\r\n\x05\x61ngle\x18\x02 \x01(\x05\x12?\n\tdirection\x18\x03 \x01(\x0e\x32,.wallu.motor_requests.MotorRequest.Direction\"6\n\tDirection\x12\x0e\n\nSTATIONARY\x10\x00\x12\x0b\n\x07\x46ORWARD\x10\x01\x12\x0c\n\x08\x42\x41\x43KWARD\x10\x02\x62\x06proto3'
)



_MOTORREQUEST_DIRECTION = _descriptor.EnumDescriptor(
  name='Direction',
  full_name='wallu.motor_requests.MotorRequest.Direction',
  filename=None,
  file=DESCRIPTOR,
  create_key=_descriptor._internal_create_key,
  values=[
    _descriptor.EnumValueDescriptor(
      name='STATIONARY', index=0, number=0,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='FORWARD', index=1, number=1,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='BACKWARD', index=2, number=2,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=161,
  serialized_end=215,
)
_sym_db.RegisterEnumDescriptor(_MOTORREQUEST_DIRECTION)


_MOTORREQUEST = _descriptor.Descriptor(
  name='MotorRequest',
  full_name='wallu.motor_requests.MotorRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='throttle', full_name='wallu.motor_requests.MotorRequest.throttle', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='angle', full_name='wallu.motor_requests.MotorRequest.angle', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='direction', full_name='wallu.motor_requests.MotorRequest.direction', index=2,
      number=3, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
    _MOTORREQUEST_DIRECTION,
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=47,
  serialized_end=215,
)

_MOTORREQUEST.fields_by_name['direction'].enum_type = _MOTORREQUEST_DIRECTION
_MOTORREQUEST_DIRECTION.containing_type = _MOTORREQUEST
DESCRIPTOR.message_types_by_name['MotorRequest'] = _MOTORREQUEST
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

MotorRequest = _reflection.GeneratedProtocolMessageType('MotorRequest', (_message.Message,), {
  'DESCRIPTOR' : _MOTORREQUEST,
  '__module__' : 'motor_requests_pb2'
  # @@protoc_insertion_point(class_scope:wallu.motor_requests.MotorRequest)
  })
_sym_db.RegisterMessage(MotorRequest)


# @@protoc_insertion_point(module_scope)
