# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: target.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='target.proto',
  package='wallu.target',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x0ctarget.proto\x12\x0cwallu.target\"\x16\n\x05\x43oord\x12\r\n\x05\x63oord\x18\x01 \x03(\x01\"A\n\x06Target\x12\r\n\x05\x63olor\x18\x01 \x01(\t\x12(\n\x0b\x63oordinates\x18\x02 \x03(\x0b\x32\x13.wallu.target.Coord\".\n\x05Scene\x12%\n\x07targets\x18\x01 \x03(\x0b\x32\x14.wallu.target.Targetb\x06proto3'
)




_COORD = _descriptor.Descriptor(
  name='Coord',
  full_name='wallu.target.Coord',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='coord', full_name='wallu.target.Coord.coord', index=0,
      number=1, type=1, cpp_type=5, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=30,
  serialized_end=52,
)


_TARGET = _descriptor.Descriptor(
  name='Target',
  full_name='wallu.target.Target',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='color', full_name='wallu.target.Target.color', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='coordinates', full_name='wallu.target.Target.coordinates', index=1,
      number=2, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=54,
  serialized_end=119,
)


_SCENE = _descriptor.Descriptor(
  name='Scene',
  full_name='wallu.target.Scene',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='targets', full_name='wallu.target.Scene.targets', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=121,
  serialized_end=167,
)

_TARGET.fields_by_name['coordinates'].message_type = _COORD
_SCENE.fields_by_name['targets'].message_type = _TARGET
DESCRIPTOR.message_types_by_name['Coord'] = _COORD
DESCRIPTOR.message_types_by_name['Target'] = _TARGET
DESCRIPTOR.message_types_by_name['Scene'] = _SCENE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Coord = _reflection.GeneratedProtocolMessageType('Coord', (_message.Message,), {
  'DESCRIPTOR' : _COORD,
  '__module__' : 'target_pb2'
  # @@protoc_insertion_point(class_scope:wallu.target.Coord)
  })
_sym_db.RegisterMessage(Coord)

Target = _reflection.GeneratedProtocolMessageType('Target', (_message.Message,), {
  'DESCRIPTOR' : _TARGET,
  '__module__' : 'target_pb2'
  # @@protoc_insertion_point(class_scope:wallu.target.Target)
  })
_sym_db.RegisterMessage(Target)

Scene = _reflection.GeneratedProtocolMessageType('Scene', (_message.Message,), {
  'DESCRIPTOR' : _SCENE,
  '__module__' : 'target_pb2'
  # @@protoc_insertion_point(class_scope:wallu.target.Scene)
  })
_sym_db.RegisterMessage(Scene)


# @@protoc_insertion_point(module_scope)
